### ISSUE TITLE
Examples to update .crypto pin

### ISSUE THREAD

**Issue by shotah** [aquiladev/ipfs-action#27]
First, I am new to all of this, and you have made an awesome action! Any chance we can get an example to how we can update our crypto provide with the new hash, like Polygon or wallet? Again still fuzzy on where to automate the hash too, I've been using unstoppabledomains to update the hash but I know it pushes to Polygon and to my wallet. Just not sure how to automate this deployment further to the point of the site going live without manual intervention.

**Comment by aquiladev** [comment]
You can find more information about dapp delivery https://dapps-delivery-guide.readthedocs.io/en/latest/
Examples of action usage https://github.com/aquiladev/dapps-delivery-guide/blob/master/.github/workflows/main.yml

I did not test the action on Polygon yet, I think it will not work because of config absence for Polygon contracts.
It properly works for Ethereum Mainnet and Rinkeby for now
